name: Build White Papers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install LaTeX
      - name: Install TeX Live & latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      # Step 3: Build PDFs from .tex files in /whitepapers
      - name: Build PDF(s)
        run: |
          mkdir -p build
          for f in whitepapers/*.tex; do
            echo "Building $f..."
            latexmk -pdf -interaction=nonstopmode -outdir=build $f
          done

      # Step 4: Upload artifacts (generated PDFs)
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdfs
          path: build/*.pdf
